# Generated by Django 5.0.1 on 2026-04-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movement", "0002_employeemovement_current_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeemovement",
            name="current_department",
        ),
        migrations.RemoveField(
            model_name="employeemovement",
            name="current_position",
        ),
        migrations.RemoveField(
            model_name="employeemovement",
            name="new_position",
        ),
        migrations.RemoveField(
            model_name="employeemovement",
            name="target_department",
        ),
    ]
