# Generated by Django 5.0.1 on 2026-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movement", "0003_remove_employeemovement_current_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeemovement",
            name="current_department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeemovement",
            name="current_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeemovement",
            name="new_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeemovement",
            name="target_department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
